name: Fetch IP list

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch-ip-list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch IP list
      run: |
        curl -s "https://api.gcore.com/cdn/public-ip-list" | jq -r '.addresses[]' > gcore.json
        curl -s https://cachefly.cachefly.net/ips/cdn.txt > cachefly.json

    - name: Commit and push if it changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        timestamp=$(date -u)
        git commit -m "Auto updated IP list on $timestamp" || exit 0
        git push
